diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filesystem.Oracle Corporation|1.8.0_271|410678281.timestampresolution=1001 microseconds
filesystem.Oracle Corporation|1.8.0_271|410678281.minracythreshold=0 nanoseconds
user.email=ranaswe2@gmail.com
user.name=ranaswe2
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/ranaswe2/Design-Pattern.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
user.name=ranaswe2
user.email=ranaswe2@gmail.com
